#!/usr/bin/env python
import gtk
import wnck
import sys

def halfwin(k):
    screen = wnck.screen_get_default()
    while gtk.events_pending(): gtk.main_iteration()

    win = screen.get_active_window()
    h = screen.get_height() 
    # wmargin = 58
    wmargin = 0
    w = screen.get_width() - wmargin
    if w > 2560:
        w = 2560
    mainw = w - 650
    if win.is_maximized() and k != 'top':
        win.unmaximize()
    if win.is_minimized():
        win.unminimize()

    def resize(x, y, w, h):
        win.set_geometry(wnck.WINDOW_GRAVITY_CURRENT, 0xffffffff, x + wmargin, y, w, h)

    if k == "top" and not win.is_maximized():
        win.maximize();
    elif k == "left":       
        resize(0, 0, w/2, h)
    elif k == "right":      
        resize(w/2 + 1, 0, w/2 - 1, h)
    elif k == '3left':      
        resize(0, 0, w/3, h)
    elif k == '3middle':   
        resize(w/3, 0, w/3, h)
    elif k == '3right':   
        resize(2*w/3, 0, w/3, h)
    elif k == 'topleft':   
        resize(0, 0, w/2, h/2)
    elif k == 'topright':  
        resize(w/2, 0, w/2, h/2)
    elif k == 'botleft': 
        resize(0, h/2, w/2, h/2)
    elif k == 'botright':
        resize(w/2, h/2, w/2, h/2)
    elif k == 'focus':
        ww = 1200
        topmargin = 50
        botmargin = 100
        resize(w/2 - ww/2, topmargin, ww, h - topmargin - botmargin)
    elif k == 'main':
        resize(0, 0, mainw, h)
    elif k == 'side':
        resize(mainw, 0, w - mainw, h)

def main():
    argv = sys.argv
    if len(argv) <= 1:
        pass
    halfwin(argv[1])
    
if __name__ == '__main__':
    main()
